### ISSUE TITLE
Prototype of the app

### ISSUE THREAD

**Issue by Vaishnavi-Markunde** [Google-Developer-Student-Club-CCOEW/Android#1]
Create a detailed prototype for the given theme

**Comment by sayli2003** [comment]
Sayli Borole
CCOEW
Computer SY
Which Activity is supposed to be used?
Should the Prototype make use of databases?
i look forward to your reply.

**Comment by Vaishnavi-Markunde** [comment]
> Sayli Borole CCOEW Computer SY Which Activity is supposed to be used? Should the Prototype make use of databases? i look forward to your reply.

Prototype refers to the design of the application (how an working app would look like) . You can use figma, canvas , paint or any other designing software

Here's a sample prototype of the website for your reference:
https://www.figma.com/file/eJCYv1psgah7fwqRZByzVP/home-page?node-id=0%3A1

**Comment by sayli2003** [comment]
Can you issue this to me?
I want to work on it

**Comment by ManasiGDeshmukh** [comment]
Manasi Deshmukh 
CCOEW
Computer
I would like to work on this issue
Can you assign it to me?

**Comment by Vaishnavi-Markunde** [comment]
@sayli2003 @ManasiGDeshmukh  
I have assigned this issue to both of you.
You can work individually or choose to collaborate.
Good luck!

**Comment by ManasiGDeshmukh** [comment]
sent a pull request @Vaishnavi-Markunde

**Comment by sayli2003** [comment]
Sent a pull request #9   @Vaishnavi-Markunde
