### ISSUE TITLE
Create a login page

### ISSUE THREAD

**Issue by Vaishnavi-Markunde** [Google-Developer-Student-Club-CCOEW/Android#2]
- Navigate to ExpenseTrackerSystem/ExpenseTrackerSystem/app/src/main/java/com/example/expensetrackersystem
- Write your code in LoginActivity.kt file

**Comment by sanikachavan18** [comment]
Sanika Chavan
Mksss Cummins College of Engineering 
Computer
I would like to work on this issue

**Comment by Vaishnavi-Markunde** [comment]
> Sanika Chavan Mksss Cummins College of Engineering Computer I would like to work on this issue

Assigned 
Good luck!
